spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: local
  application:
    name: '@project.name@'

couchbase-config:
  connection-string: couchbase://127.0.0.1
  user-name: Administrator
  password: password
  bucket-PDFStore:
    name: PDFStore
    user-name: PDFStore
    password: password

server:
  port: 8080

